### ISSUE TITLE
Bold button bug when delete all and write first line

### ISSUE THREAD

**Issue by maxiplay** [miztroh/wysiwyg-e#110]
Open demo 

[https://miztroh.github.io/bower_components/wysiwyg-e/](url)

Select all and remove. Bold is becomed black. (Why ?)

Then write text without clicking anywhere and click on bold to disabled.

Type a letter. The cursor go to bottom and text stay bold

**Comment by miztroh** [comment]
When you clear all, the top line is an h1 because of the heading that's there initially.  To remove the heading, you have to press backspace one more time.  Headings are always detected as bold and cannot be additionally bolded by the underlying JS API.

Try ``document.queryCommandState('bold')`` and ``document.execCommand('bold')`` while a heading element is selected.

**Comment by maxiplay** [comment]
ok :+1:
