### ISSUE TITLE
Add / remove event listeners via attached / detached callbacks

### ISSUE THREAD

**Issue by aletorrado** [miztroh/wysiwyg-e#122]
I've noticed some ```addEventListener``` calls without their matching ```removeEventListener```, for example in ```wysiwyg-tool-audio```. Is this ok?

**Comment by miztroh** [comment]
While the events are only added once when the element becomes ready, it is true that they would not be garbage collected when the element is detached from the DOM.  If you're creating and destroying lots of an affected element like ``wysiwyg-tool-audio``, there might be performance implications.  Will address.

**Comment by aletorrado** [comment]
The last commit is wrong. The listeners are binded twice, once for attached and once for detached, so new functions are created and references don't match. You should store the binded function and remove that same function reference.

**Comment by miztroh** [comment]
Agree with assessment about storing reference to handlers.  Where do you see listeners are added twice?

**Comment by aletorrado** [comment]
They're not added twice. They're just binding twice `this` to `wysiwyg-tool-audio`.

**Comment by aletorrado** [comment]
This same issue is repeated in the video tool, when attaching `click` and `keydown` handlers to the document. I think this issue should be labeled as `bug`, as it implies a memory leak.

**Comment by miztroh** [comment]
The resolution commit addresses all event bindings in `wysiwyg-e` and the included tools.

As for the label, I define bugs as anything that breaks the end user experience.  The original code did not break the user experience.  It did, however, pose a potential performance issue.  In resolving the issue, I have enhanced performance.  That's why this is labeled as an enhancement.
