### ISSUE TITLE
Editor FullScreen Mode

### ISSUE THREAD

**Issue by hyyan** [miztroh/wysiwyg-e#147]
Is full-screen mode planned to this project ?

Thanks

**Comment by miztroh** [comment]
Since ``wysiwyg-e`` will scale to the size of its parent, I'll probably just leave this up to implementers.  You could create a basic tool with the fullscreen icon that fires a ``wysiwyg-fullscreen`` event or something like that.  The parent node would listen for that event and take the necessary action.  Check out the following project by another ``wysiwyg-e`` implementer.  I believe he incorporates fullscreen mode.

http://writecontrol.fr/
