### ISSUE TITLE
HTML table

### ISSUE THREAD

**Issue by coco1979ka** [miztroh/wysiwyg-e#160]
It would be very helpful to have a support for HTML tables.
Clicking on the table item should open a menu to select how many rows and columns are needed.
After that it should also be possible to add/insert/delete lines or columns.

**Comment by RoXuS** [comment]
+1

**Comment by jpicus** [comment]
+1

**Comment by ThibzThibz** [comment]
+1

**Comment by jpicus** [comment]
Hi,

Any hope to see this feature in a near future ?

Regards

**Comment by miztroh** [comment]
It's in the works.  There's a lot of functionality in this tool compared to the others, so it might not be ready until the Polymer 3.0 time frame.  Regardless, I'll backport it to 2.x.

![screenshot from 2018-01-16 16-32-40](https://user-images.githubusercontent.com/2515209/35015652-ebe2b74c-fada-11e7-9a51-4abd11d63d9c.png)

**Comment by miztroh** [comment]
I've got **good news** and **bad news**.

**Good news:** I powered through the work on the new table tool.  See the animated GIF below and the ``3.0-preview`` branch [code](https://github.com/miztroh/wysiwyg-e/blob/d9817ce6ed5401d8fffccaceb60e8617714325af/tools/table.js).

**Bad news:** The ``3.0-preview`` branch includes several changes to the editor and tools that make porting this tool back to 2.0 non-trivial.  First, tools now have their own ``allowedStyleTypes`` property so that the editor doesn't have to manage all the possible styles required by all possible tools.  Second, tools now have their own ``sanitize`` method that gets called whenever a mutated DOM node's tag name is a member of the tool's ``allowedTagNames`` property.  This allows tools to sanitize their respective content (e.g. the table tool can sanitize ``table``, ``tr``, ``td``, etc.).  In general, I'm trying to keep what the editor has to manage as simple as possible while giving more power to individual tools (and tool authors :+1: ).  However, I won't be trying to port all that functionality (or the table tool) back to 2.x.  Thankfully, Polymer 3.0 should be coming out sooner rather than later.

![localhost_3000_record html 1](https://user-images.githubusercontent.com/2515209/35238191-66f7198c-ff72-11e7-98e7-80334803ba9a.gif)

I'm going to go ahead and close this issue.  Feel free to add comments if you see any important functionality I've missed.  I've intentionally kept all the interface within the tool dropdown itself instead of making an interface appear within the table(s).
