### ISSUE TITLE
Drag and Drop Feature for upload

### ISSUE THREAD

**Issue by jfdevradius** [miztroh/wysiwyg-e#189]
Hello, 

I was wondering if a drag and drop feature is in the works or will be in the future for uploading files using the wysiwyg-e components

**Comment by miztroh** [comment]
Since any uploading of files would require a server-side component, I have no plans at this time to implement this.  However, you could certainly write your own tool based on ``wysiwyg-tool``.  Tools are made aware of the target node, so you could implement a tool that adds event handlers for drag / drop.
