### ISSUE TITLE
Add grammar checking

### ISSUE THREAD

**Issue by maxiplay** [miztroh/wysiwyg-e#72]

**Comment by miztroh** [comment]
@maxiplay Don't most browsers have this built in?

**Comment by maxiplay** [comment]
Perhaps my formulation is not enough precise. I would like to have conjugation, grammar corrections etc..

**Comment by miztroh** [comment]
Ah.  I will consider PRs for this.

**Comment by maxiplay** [comment]
After some research, it seems only server side solutions are availables. It require big dictionnaries and big treatments. The best solution I found is https://languagetool.org/. It's open source code in java and use Lucene, like Elastic Search.It's based on HUNSPELL. There is ~20 languages managed. 

Can we imagine an UI integration of ajax request to get a list of "match" errors ?  With error highlighted and proposals ?  Or Do you think that it is outside the scope of your project ? I can eventually contribute but I'm afraid about possible complexity for entering in your project.

**Comment by miztroh** [comment]
``wysiwyg-e`` is designed such that every tool (plugin) gets notified when the content changes.  As such, you could write a tool to fire AJAX requests to check the new content.  However, you couldn't display any grammar errors inside of the content itself because that would change the content.  Any errors would have to be displayed in an overlay, which might prove to be difficult, especially when scrolling.

**Comment by maxiplay** [comment]
Accept to change content to have grammar checking could be an option choosen by user with a tool button. I imagine a span around the text in error with a specific style like red underline ( style could depend on css variable). When user unset tool the html is sanitize from grammar checking span. If there is a function that give the pure text without html code we wouldn't have two AJAX requested because the pure text would not change. We also need to have pure text without HTML in order to send it to grammar/spell checker. For test without server we can use a light dictionnary.

**Comment by miztroh** [comment]
Since this is likely to require utilization of a third-party service, I'm not inclined to develop this as part of the core package.  However, I would be willing to make improvements to the core package that allow for easier integration of features like this.  If this is something you care to work on, just let me know what roadblocks you encounter in terms of integration with ``wysiwyg-e``.  For now, I'm closing this as a ``wontfix``.

**Comment by maxiplay** [comment]
Yes I understand your point of view. I will do it with a parent element of my instance of wysiwyg-e and if there is an integration problem, I will let you know, but I think none will occur. Thanks for the discussion.
