### ISSUE TITLE
Paste images to body; ability to attach files

### ISSUE THREAD

**Issue by Analect** [miztroh/wysiwyg-e#81]
@miztroh 
Thanks for this nice tool. Are there any plans to allow for images to pasted directly (rather than having to hit the image and then embed a url to an image location).  Also, is the ability to add file attachments on the roadmap anywhere? Thanks.

**Comment by miztroh** [comment]
Pasting should already work.  I just copied your avatar and pasted it into the demo.  Works in Chrome anyway.

https://miztroh.github.io/bower_components/wysiwyg-e/demo/index.html?value=%3Cimg+src%3D%22https%3A%2F%2Favatars2.githubusercontent.com%2Fu%2F4063815%3Fv%3D3%26amp%3Bs%3D96%22+alt%3D%224063815+%2896%C3%9796%29%22%3E

No plans to incorporate file attachments, as that doesn't really fit within the notion of a WYSIWYG editor.  The editor exposes a basis ``value`` property containing the HTML content.  I see a file uploads / attachments as being a separate piece of functionality.

**Comment by Analect** [comment]
@miztroh 
Thanks.  It seems an image needs to have a URL for it to work though ... if I just use something like a snipping tool or screen-capture on a mac and then try to paste from the clipboard ... it doesn't appear to work. Is that the expected behaviour?

![image](https://cloud.githubusercontent.com/assets/4063815/16056955/abf3e960-326f-11e6-9778-8368bf26c8a4.png)

Ref. attachments ... understood ... thanks anyway.  I don't suppose you're aware of another polymer-based editor out there that handles attachments?

**Comment by miztroh** [comment]
In order to display an image, a URL would have to be involved.  For example, if I take a Word document with text and images and copy / paste it into a WYSIWYG editor, only the text comes through.  Image placeholders are there, but not the actual images.

I am interested in expanding the functionality of the image tool to allow you to "upload" images to the editor in the form of base64-encoded strings.  Does that cover your needs or are you looking to upload other kinds of files?

As I said before, uploading non-image content is a separate set of functionality.  You could find or create a file upload custom element, then compose it with a WYSIWYG custom element to create your own element that offers both.

**Comment by Analect** [comment]
@miztroh 
I was previously using something called redactor (https://imperavi.com/redactor/) where I had it set up such that pasted images and file attachments were pushed to a mongodb gridfs file-system ... and then placeholders (of form embedded or attached) with relevant identifers were used to reference those files.

I was hoping to get this working in a polymer context and maybe use something like https://github.com/vaadin/vaadin-upload for uploading files/images.

**Comment by miztroh** [comment]
You could certainly do this with ``wysiwyg-e``.  Basically, you'd create a custom tool to replace the provided image tool.  Your tool would let users upload an image, then let them browse uploaded images to insert one into the content.

You could do the same for file uploads.  Write a custom tool that allows users to upload a file.  Then, they can browse their uploaded files and select one.  Whenever they select one, it would insert some sort of snippet into the content (e.g. an image icon representing the file type with a link showing the file name).

The reason I won't develop this as part of the core package is because I'm not providing any sort of backend where the files would actually be stored.  This sort of thing would have to be tailored to a specific backend.

**Comment by Analect** [comment]
FYI, there are a few other demos out there that are handling the provision of local backend quite eloquently, such as this demo from vaadin, where [pouchdb](https://github.com/vaadin/expense-manager-demo/blob/master/app/elements/overview-page.html#L112) is being used to [handle](https://github.com/vaadin/expense-manager-demo/blob/master/app/elements/expense-editor.html#L194-200) uploads. I notice that the new core App Element have also introduced a [pouchdb](https://elements.polymer-project.org/elements/app-pouchdb) element to handle off-network/offline capabilities.

https://vaadin.github.io/expense-manager-demo

![image](https://cloud.githubusercontent.com/assets/4063815/16058874/5e1a9622-3278-11e6-85a5-f0bfa9bb8d8f.png)

**Comment by miztroh** [comment]
Sure.  There are lots of great reasons to incorporate image / file uploads.  That's why I made ``wysiwyg-e`` modular in that everything in the toolbar is a tool plugin.  You can create your own based on the tool behavior it provides.  I'm all for third-party tools.

As for the core functionality, I have to draw the line somewhere.  I see no added value in spending time developing a demo utilizing local storage.  That doesn't help most real world applications.  For remote storage, it's backend-specific.  You could develop tool plugins for a specific backend or multiple / configurable backends.  Those features are great, but not central to this element's functionality.

**Comment by Analect** [comment]
Understood.
